name: TestNG API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Show Java and Maven versions
        run: |
          java -version
          mvn -version

      - name: List project files
        run: |
          echo "=== Project Structure ==="
          ls -la
          echo "=== TestNG XML ==="
          cat testng.xml
          echo "=== Test Classes ==="
          find src/test -name "*.java" -type f

      - name: Run TestNG Tests
        run: mvn clean test -DsuiteXmlFile=testng.xml

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            target/surefire-reports/
            target/site/allure-maven-plugin/
          retention-days: 7

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/
          retention-days: 30