name: Debug Workflow

on:
  push:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug Information
      run: |
        echo "=== Debug Information ==="
        echo "Branch: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"
        echo "Repository: ${{ github.repository }}"
        echo "Workflow: ${{ github.workflow }}"
        echo "=== File Structure ==="
        find . -type f -name "*.yml" -o -name "*.yaml" | head -10
        echo "=== Current Directory ==="
        pwd
        ls -la 