name: Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Show Java version
      run: java -version
      
    - name: Show Maven version
      run: mvn -version
      
    - name: List files
      run: ls -la
      
    - name: Check if pom.xml exists
      run: |
        if [ -f "pom.xml" ]; then
          echo "pom.xml found"
          cat pom.xml | head -10
        else
          echo "pom.xml not found"
          find . -name "*.xml" -type f
        fi 